notifications:
  slack: wtsi-cgpit:ptUMR1tkNyZJYd9TpGoss8WR
  email: false

sudo: false

services:
  - docker

cache:
  directories:
  - docker

script:
 - set -e
 - echo 'Build and check docker image'
 - docker build -t github_graph .
 - docker images | grep -c github_graph
